### ISSUE TITLE
generateDate Change 

### ISSUE THREAD

**Issue by zivkaplan** [yishayhaz/paca-paca#2]
Currently the eval() function is used to generated dates, and that it is a way to let let the user run code on your server side. 

```js
  const generateDate = (dateStr) =>
        eval(
            `new Date(Math.floor(Math.random() * 2550000000000)).${
                dateStr.slice(5) || "toISOString()"
            }`
        );
```

I suggest maybe changind the interface for dates : 

```js
let data = {
  createdAt: { type: "date" },                               // Will return random date between 1970-2050
  createdAt: { type: "date" , option: "month"  },  // .getMonth()
  createdAt: { type: "date" , option: "time"  }      // .getTime()
}
```

This solution isn't ideal. since it makes an API change and isn't backwards compatibilty. 
What is your thought?

:)

**Comment by yishayhazan** [comment]
I know it's problematic, I think I will just remove this option and send Unix time instead, and the user will have to convert it on his end (just like in real life),
but I remember when I wrote this update, I have considered this option, and I tried "hacking" my back-end,
but because the whole code is wrapped in try-catch block, it works fine (if you don't send valid time-function)

try this: `"date": "date.getTime(); console.log(VariableThatDoesntExist)"` // this should crash the server (I think)
but if you know better, let me know,
and thank you for the report!
